/*
 * 1Password Connect
 *
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@1password.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct File {
    /// ID of the file
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the file
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Size in bytes of the file
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// Path of the Connect API that can be used to download the contents of this file.
    #[serde(rename = "content_path", skip_serializing_if = "Option::is_none")]
    pub content_path: Option<String>,
    #[serde(rename = "section", skip_serializing_if = "Option::is_none")]
    pub section: Option<Box<crate::raw::models::FileSection>>,
    /// Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl File {
    pub fn new() -> File {
        File {
            id: None,
            name: None,
            size: None,
            content_path: None,
            section: None,
            content: None,
        }
    }
}
