/*
 * 1Password Connect
 *
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@1password.com
 * Generated by: https://openapi-generator.tech
 */

/// `FileSection` : For files that are in a section, this field describes the section.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileSection {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl FileSection {
    /// For files that are in a section, this field describes the section.
    pub fn new() -> FileSection {
        FileSection { id: None }
    }
}
