/*
 * 1Password Connect
 *
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@1password.com
 * Generated by: https://openapi-generator.tech
 */

/// `GeneratorRecipe` : The recipe is used in conjunction with the \"generate\" property to set the character set used to generate a new secure value
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeneratorRecipe {
    /// Length of the generated value
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    #[serde(rename = "characterSets", skip_serializing_if = "Option::is_none")]
    pub character_sets: Option<std::collections::HashSet<CharacterSets>>,
}

impl GeneratorRecipe {
    /// The recipe is used in conjunction with the \"generate\" property to set the character set used to generate a new secure value
    pub fn new() -> GeneratorRecipe {
        GeneratorRecipe {
            length: None,
            character_sets: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
#[allow(clippy::upper_case_acronyms)]
pub enum CharacterSets {
    #[serde(rename = "LETTERS")]
    LETTERS,
    #[serde(rename = "DIGITS")]
    DIGITS,
    #[serde(rename = "SYMBOLS")]
    SYMBOLS,
}

impl Default for CharacterSets {
    fn default() -> CharacterSets {
        Self::LETTERS
    }
}
