/*
 * 1Password Connect
 *
 * REST API interface for 1Password Connect.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@1password.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "name")]
    pub name: String,
    /// The Connect server's version
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Vec<crate::raw::models::ServiceDependency>>,
}

impl InlineResponse200 {
    pub fn new(name: String, version: String) -> InlineResponse200 {
        InlineResponse200 {
            name,
            version,
            dependencies: None,
        }
    }
}
